### ISSUE TITLE
TypeError: refNode.lookupPrefix is not a function

### ISSUE THREAD

**Issue by loretoparisi** [ubear/hegel#3]
```
[loretoparisi@:mbploreto hegel]$ node server.js 
post at /render/: 2017-11-15T12:51:26+01:00
/hegel/node_modules/xmldom/dom.js:925
		var prefix = refNode.lookupPrefix(uri);
		                     ^

TypeError: refNode.lookupPrefix is not a function
    at nodeSerializeToString (/hegel/node_modules/xmldom/dom.js:925:24)
    at XMLSerializer.serializeToString (/hegel/node_modules/xmldom/dom.js:914:31)
    at Object.exports.renderSvgToPng (/hegel/chart/render.js:180:47)
    at Object.done (/hegel/server.js:37:14)
    at //hegel/node_modules/jsdom/lib/jsdom.js:249:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

The http call was

```
POST
{
  "width": "400",
  "height": "200",
  "units": "%", 
  "stokeColor": "green",
  "stokeWidth": 2,
  "filename": "percentage.png",
  "data":[[1445749500.0, 100.0], 
          [1445749800.0, 100.0], 
          [1445750100.0, 100.0], 
          [1445750400.0, 100.0], 
          [1445750700.0, 100.0],
          [1445751000.0, 100.0]
        ]
}
```

**Comment by loretoparisi** [comment]
**[UPDATE]**
I thinks this was due to the version of `xmldom` so I have moved the the one in the `package.json`, that was `"xmldom": "0.1.19"`, but this time I get a 

```
[loretoparisi@:mbploreto hegel]$ node server.js 
post at /render/: 2017-11-15T13:01:36+01:00
percentage.svg to percentage.png failed. { Error: Command failed: /hegel/node_modules/phantomjs/lib/phantom/bin/phantomjs /hegel/node_modules/svg2png/lib/converter.js percentage.svg percentage.png 1

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: null,
  signal: 'SIGSEGV',
  cmd: 'hegel/node_modules/svg2png/lib/converter.js percentage.svg percentage.png 1' }
```

**Comment by mahdizar** [comment]
Hi

I think it works with "xmldom": "0.1.18"

HTH
